language: haxe

before_install:
   - haxelib install lime
   - haxelib install nme
   - haxelib install openfl
   - haxelib install starling
   - haxelib install as3hx

script:
   - haxelib run lime build "haxe/PipeJam3/project.xml" html5 -release -Dfdb
   - haxelib run lime build "haxe/FlowJam/project.xml" html5 -release -Dfdb