/**
 * NOTE: This file was automatically generated by script/buildInfo.py.
 */

package buildInfo;


class BuildInfo
{
    public static inline var DATE : String = "20151216";
    public static inline var VERSION : String = "85b257e7a14a";

    public function new()
    {
    }
}

