/**
 * NOTE: This file was automatically generated by script/buildInfo.py.
 */

package buildInfo
{
	public class BuildInfo
	{
		public static const DATE:String = "20180503";
		public static const VERSION:String = "unknown";
	}
}
