/**
 * NOTE: This file was automatically generated by script/buildInfo.py.
 */

package buildInfo
{
	public class BuildInfo
	{
		public static const DATE:String = "20151216";
		public static const VERSION:String = "85b257e7a14a";
	}
}
