import datetime, os, sys

buildinfotemplate = '''\
/**
 * NOTE: This file was automatically generated by script/buildInfo.py.
 */

package buildInfo
{
	public class BuildInfo
	{
		public static const DATE:String = "%(builddate)s";
		public static const VERSION:String = "%(buildversion)s";
	}
}
'''

def main(args):
	if sys.platform == 'win32':
		hgcmd = 'hg id -i';
	else:
		hgcmd = 'bash -l -c "hg id -i"';

	buildversion = os.popen(hgcmd).read().strip() or 'unknown'
	builddate = datetime.date.today().strftime('%Y%m%d')

	path = os.path.dirname(os.path.realpath(__file__)) + '/../src/buildInfo'

	if not os.path.exists(path):
		os.makedirs(path)

	f = open(path + '/BuildInfo.as', 'w')
	f.write(buildinfotemplate % vars())
	f.close()

if __name__ == '__main__':
	main(sys.argv)
